name: "易观博客"
description: "Tanky Woo's Blog, focus on Python, Linux, Gentoo, Mac OS, Vim, Open Source and so on."
url: "https://692.github.io"
markdown: redcarpet
pygments: true
exclude: ["fabfile.py*", "*.bak"]
